language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-fullstack-crud' ]; then cd .. && eval "mv $currentfolder generator-angular-fullstack-crud" && cd generator-angular-fullstack-crud; fi

